<?php  /** @var $block \Magento\Checkout\Block\Cart\Sidebar */ ?>
<div data-block="minicart" class="minicart-wrapper">
	<a class="action showcart title-cart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
	   data-bind="scope: 'minicart_content'">
		<span class="counter qty empty"
				  data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
			<span class="icon">
				<i class="meigee-cart"></i>
			</span>
			<span class="text"><?php /* @escapeNotVerified */ echo __('Cesta'); ?></span>
			<span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
			<span class="counter-label">
			<!-- ko if: getCartParam('summary_count') -->
				<!-- ko text: getCartParam('summary_count') --><!-- /ko -->
				<!-- ko i18n: 'items' --><!-- /ko -->
			<!-- /ko -->
			</span>
		</span>
	</a>
	<?php if ($block->getIsNeedToDisplaySideBar()): ?>
<!-- 2018-04-26 I have added the `cart-summary` class to style the «Estimate Shipping and Tax» block. -->
		<div class="block block-minicart empty cart-summary"
			 data-role="dropdownDialog"
			 data-mage-init=
			'{"dropdownDialog":{
			"triggerEvent" : "hover",
			"appendTo":"[data-block=minicart]",
			"triggerTarget":".showcart",
			"closeOnMouseLeave": false,
			"closeOnEscape": true,
			"triggerClass":"active",
			"parentClass":"active",
			"buttons":[]}}'>
<!-- 2018-04-26 I have added the `minicart.addons` line below. -->
			<?= $block->getChildHtml('minicart.addons') ?>
			<div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
				<!-- ko template: getTemplate() --><!-- /ko -->
			</div>
		</div>
	<?php endif ?>
	<script>
		window.checkout = <?= /* @escapeNotVerified */ $block->getSerializedConfig() ?>;
	</script>
	<script type="text/x-magento-init">
	{
		"[data-block='minicart']": {
			"Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
		},
		"*": {
			"Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
		}
	}
	</script>

</div>

